---
title: "First trial"
author: "Camila Vargas"
date: "2/16/2018"
output: html_document
---

## Outline for Final Collab Website


### Tabs/Subsections:

### Home
The home page of our website we envision as being a timeline with our progress on the OHI adventure. The timeline will be a vertical line, the top being time 0 (January 2018, when we started learning the necesary tools), and the bottom being x (September 2018, when we finally have OHI scores!). Along the timeline we think on having different points showing our achievements, issues, problems, comments through out the process. These notes are going to be devided in the following section (each one representig a tab of the website): Blog, R &Rmarkdown, Github and OHI Theory. The description of each tab/section is describing bellow.

***

### Blog

The OHI fellows will take turns updating the blog with posts about our experience learning how to calculate the Ocean Health Index, navigate data science, and interesting happenings in our day-to-day.

***

### R & Rmarkdown

This page will contain posts about how we use RStudio and Rmarkdown including: 

* Challenges we faced and how we resolved them
* Cheatsheets we make about using Rmarkdown to make webpages or collaborative documents
* General tips on how to set up and start using RStudio and Rmarkdown for collaborative science!

***

### Github

This page will contain GitHub tips and troubleshooting articles relevant to the OHI project:

* common GitHub issues and how we troubleshooted them
* GitHub cheatsheets for working on the OHI project
* How we use GitHub in OHI

***

### OHI Theory

In this section we will be describing our process on learning about what is the OHI, how is it calculates, what are all the goals about and how is each goal score calculated. We would like to share witht the community our questions and how we answer them. Also, provide materials that has been usefull for us to have a clear undertanding of the index.  

***

### Merge Trial Section...

Hi this is a place to test out/learn about merge conflicts 
I don't know why but I wanted to add some stuff in between Ellie's lines (Iwen).

someone else write stuff in this section...

Also am going to add stuff here too to try and make things difficult (Iwen).











